name: Build and deploy Node.js app to Azure Web App - MagicFormatter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Use `npm ci` for reproducible builds instead of `npm install`

      - name: Build TypeScript
        run: npm run build # Ensure this compiles TS to JS (e.g., outputs to `dist/`)

      - name: Prune dev dependencies
        run: npm prune --production # Remove dev dependencies

      - name: Zip deployment artifact
        run: |
          zip -r release.zip ./* -x "*.git*" -x "*.github*" -x "node_modules/*"
          # Include only necessary files (e.g., `dist/`, `package.json`, `.env.production`)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d deployment-files

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # Rename secrets for clarity
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MagicFormatter'
          slot-name: 'Production'
          package: deployment-files # Point to the unzipped folder
          # If your app uses a startup file (e.g., `dist/index.js`), set this in Azure:
          # startup-command: 'npm start'